version: "3"

services: 
  mysql_knex:
    container_name: BancoDoProjeto
    hostname: BancoDoProjeto
    image: mysql
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    volumes: 
      - C:\Users\Paolo Klahold\Desktop\Faculdade\BaseDeDados:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: base_de_dados
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
      TZ: America/Sao_Paulo
    networks:
      - minha_rede

  apache_php:
    container_name: MeuProjetoWeb
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./seu_codigo:/var/www/html
    depends_on:
      - mysql_knex
    networks:
      - minha_rede

networks:
  minha_rede:
    driver: bridge
